export const DEFAULT_SHOP_CONFIG = {
  baselineAovCents: 1000,
  freeShippingThresholdCents: 2000,
  milestonesJson: [
    { amount: 2000, label: "10% OFF" },
    { amount: 5000, label: "15% + Gift" },
    { amount: 10000, label: "Free Gift" },
  ],
  enableCrossSell: true,
  enableMilestones: true,
  enableCouponTease: true,
  plan: "basic",
  billingStatus: "inactive",
  recommendationStrategy: "COLLECTION_MATCH",
  manualCollectionIds: [] as string[],
  recommendationLimit: 1,
  primaryColor: "#111111",
  accentColor: "#16a34a",
  borderRadius: 12,
  showConfetti: true,
  countdownEnabled: true,
  emojiMode: true,
  engineVersion: "v3",
};
